"""
Django settings for Raplev project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from datetime import timedelta
from raplev.settings import *

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
        'ATOMIC_REQUESTS': True,
    }
}

STATIC_URL = '/static/'
STATIC_ROOT = '/home/ion/Work/Omar/test/static'

MEDIA_URL = '/media/'
MEDIA_ROOT = '/home/ion/Work/Omar/test/media'

EMAIL_FILE_PATH = '/home/ion/Work/Omar/test/emails'
